server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphql?characterEncoding=utf8&enabledTLSProtocols=TLSv1.2
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: graphql
  graphql:
    graphiql:
      enabled: true